package dot.java.moldel;

import java.sql.*;

public class UserTable {

	public static int usertable() {
		try {
//			ALTER TABLE `orderbill` ADD `billPaid` VARCHAR(255) NULL DEFAULT NULL AFTER `payment`, ADD `discountPer` VARCHAR(255) NULL DEFAULT NULL AFTER `billPaid`, ADD `discount` VARCHAR(255) NULL DEFAULT NULL AFTER `discountPer`, ADD `shippingCharge` VARCHAR(255) NULL DEFAULT NULL AFTER `discount`;
			String productTable = "CREATE TABLE `products` (\r\n"
					+ "  `id` int(10) NOT NULL,\r\n"
					+ "  `productName` varchar(255) DEFAULT NULL,\r\n"
					+ "  `category` varchar(255) DEFAULT NULL,\r\n"
					+ "  `price` varchar(25) DEFAULT NULL,\r\n"
					+ "  `activeStatus` varchar(255) DEFAULT NULL,\r\n"
					+ "  `imageAddress` text DEFAULT NULL\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";
			String AddressTable = "CCREATE TABLE `addressusers` (\r\n"
					+ "  `id` int(10) NOT NULL,\r\n"
					+ "  `address` text DEFAULT NULL,\r\n"
					+ "  `city` varchar(100) DEFAULT NULL,\r\n"
					+ "  `state` varchar(100) DEFAULT NULL,\r\n"
					+ "  `country` varchar(255) DEFAULT NULL,\r\n"
					+ "  `mobileNumber` varchar(12) DEFAULT NULL,\r\n"
					+ "  `email` varchar(255) DEFAULT NULL,\r\n"
					+ "  `created_at` timestamp NULL DEFAULT current_timestamp()\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";
			String CardTable = "REATE TABLE `usercards` (\r\n"
					+ "  `id` int(10) NOT NULL,\r\n"
					+ "  `email` varchar(100) DEFAULT NULL,\r\n"
					+ "  `product_id` int(10) DEFAULT NULL,\r\n"
					+ "  `quantity` varchar(30) DEFAULT NULL,\r\n"
					+ "  `price` varchar(40) DEFAULT NULL,\r\n"
					+ "  `total` varchar(255) DEFAULT NULL,\r\n"
					+ "  `address_id` int(10) DEFAULT NULL,\r\n"
					+ "  `billNo` varchar(255) DEFAULT NULL,\r\n"
					+ "  `orderedDate` date DEFAULT NULL,\r\n"
					+ "  `status` varchar(20) DEFAULT NULL\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";
			String OrderTable = "CREATE TABLE `orderbill` (\r\n"
					+ "  `id` int(10) NOT NULL,\r\n"
					+ "  `email` varchar(255) DEFAULT NULL,\r\n"
					+ "  `orderDate` date DEFAULT NULL,\r\n"
					+ "  `delivaryDate` date DEFAULT NULL,\r\n"
					+ "  `payment` varchar(255) DEFAULT NULL,\r\n"
					+ "  `paymentMethod` varchar(255) DEFAULT NULL,\r\n"
					+ "  `billPaid` varchar(255) DEFAULT NULL,\r\n"
					+ "  `discountPer` varchar(255) DEFAULT NULL,\r\n"
					+ "  `discount` varchar(255) DEFAULT NULL,\r\n"
					+ "  `shippingCharge` varchar(255) DEFAULT NULL,\r\n"
					+ "  `billNo` varchar(255) DEFAULT NULL,\r\n"
					+ "  `transactionId` varchar(255) DEFAULT NULL,\r\n"
					+ "  `status` varchar(255) DEFAULT NULL,\r\n"
					+ "  `addressId` varchar(20) DEFAULT NULL\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";

			String userTable = "CREATE TABLE `user` (\r\n"
					+ "  `id` int(11) NOT NULL,\r\n"
					+ "  `name` varchar(40) DEFAULT NULL,\r\n"
					+ "  `email` varchar(100) DEFAULT NULL,\r\n"
					+ "  `mobileNumber` varchar(12) DEFAULT NULL,\r\n"
					+ "  `gender` varchar(10) DEFAULT NULL,\r\n"
					+ "  `question` varchar(255) DEFAULT NULL,\r\n"
					+ "  `answer` varchar(255) DEFAULT NULL,\r\n"
					+ "  `password` varchar(100) DEFAULT NULL\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";
			String messageBody ="CREATE TABLE `contactus` (\r\n"
					+ "  `id` int(10) NOT NULL,\r\n"
					+ "  `email` varchar(255) DEFAULT NULL,\r\n"
					+ "  `subject` varchar(255) DEFAULT NULL,\r\n"
					+ "  `message` text DEFAULT NULL\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";
			String feedBack ="CREATE TABLE `feedback` (\r\n"
					+ "  `id` int(10) NOT NULL,\r\n"
					+ "  `name` varchar(255) DEFAULT NULL,\r\n"
					+ "  `email` varchar(255) NOT NULL,\r\n"
					+ "  `feedback` text NOT NULL\r\n"
					+ ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";
			
		 String addColunm ="--\r\n"
		 		+ "-- Indexes for dumped tables\r\n"
		 		+ "--\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `addressusers`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `addressusers`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `contactus`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `contactus`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `feedback`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `feedback`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `orderbill`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `orderbill`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `products`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `products`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `user`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `user`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`),\r\n"
		 		+ "  ADD UNIQUE KEY `email` (`email`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- Indexes for table `usercards`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `usercards`\r\n"
		 		+ "  ADD PRIMARY KEY (`id`);\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for dumped tables\r\n"
		 		+ "--\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `addressusers`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `addressusers`\r\n"
		 		+ "  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `contactus`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `contactus`\r\n"
		 		+ "  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `feedback`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `feedback`\r\n"
		 		+ "  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `orderbill`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `orderbill`\r\n"
		 		+ "  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `products`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `products`\r\n"
		 		+ "  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `user`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `user`\r\n"
		 		+ "  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;\r\n"
		 		+ "\r\n"
		 		+ "--\r\n"
		 		+ "-- AUTO_INCREMENT for table `usercards`\r\n"
		 		+ "--\r\n"
		 		+ "ALTER TABLE `usercards`\r\n"
		 		+ "  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=77;\r\n"
		 		+ "COMMIT;";
			PreparedStatement ps = DB_Connection.getDBConPs(userTable);
			ps.execute();
			System.out.println(productTable);
			System.out.println(userTable);

			return 1;

		} catch (Exception e) {
			System.out.println(e);
			return 0;
		}
	}

}
